services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
